name: Terraform infra provisioning
on: [push]
jobs:
  InfraProvisioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"
      - name: Apply configurations
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          yaelwil-tf.pub: ${{ secrets.YAELWIL_TF }}
        run: |
          terraform init
          terraform plan -var-file="dev.tfvars" 
          terraform apply -var-file="dev.tfvars" -auto-approve
